### ISSUE TITLE
what's the MAX_BUSY_CYCLE mean?

### ISSUE THREAD

**Issue by rill-zhen** [nvdla/doc#3] opened 2017-10-12 02:40 UTC
what's the MAX_BUSY_CYCLE mean(mentioned in NVDLA_OpenSource_Performance.xls)? include the zero-calculations or not?

**Comment by jwise** [comment] 2017-10-13 23:24
(closing as duplicate of nvdla/hw#30)

**Closed as completed by jwise** 2017-10-13 23:24 UTC
